### ISSUE TITLE
I can not load any Pharo images on MacBook Pro

### ISSUE THREAD

**Issue by YvanGuifo** [UMMISCO/kendrick#101]
Hello,
I use a MacBook Pro (Retina, mid-2012) whose system is macOS Mojave and I can not load a pharo image. 
I tried to load Pharo 6.1 (32-bit stable version) without success.
Similarly, I tried Pharo 6.1 (64bit) and the stable version of Pharo 7.0 (64 bit). I still have this error "The process took too much time. Aborted!"

**Comment by SergeStinckwich** [comment]
Apparently this is more a Pharo issue than Kendrick issue. You don’t say how you dl Pharo ... you use PharoLauncher ?

**Comment by YvanGuifo** [comment]
Yes I use Pharolauncher. And it's true that it's a Pharo problem. Because as long as the image is not charging I can not download Kendrick

**Comment by SergeStinckwich** [comment]
I’m not sure you know how to dl, install and run app correctly on MacOS. Where you dl PharoLauncher, how&where tou install it ? As usual you need to describe what you are doing very precisely because I know that Pharo is running correctly on this computer 😀

**Comment by YvanGuifo** [comment]
I was able to solve the problem by removing the old PharoLauncher and installing a new one.
I was able to load the 6.1 version 32 bit image of Pharo. But there is a problem when I paste the code (Kendrick baseline) necessary for the installation of Kendrick and that I execute, one displays me the following error 'Error: could not find accessor for variable name' version "'

**Comment by SergeStinckwich** [comment]
This is better to use 64 bits VM. If you update MacOS to Catalina last version, 64bits app are mandatory.

**Comment by SergeStinckwich** [comment]
What is the code you paste ?

**Comment by YvanGuifo** [comment]
Metacello new
        repository: 'github://UMMISCO/kendrick:master/src';
        baseline: 'Kendrick';
        load

**Comment by SergeStinckwich** [comment]
Works for me in a Pharo 6.1 64bits VM. Did you select all the lines to execute ?

**Comment by YvanGuifo** [comment]
Yes all lines have been selected. I am updating the OS as you indicated to me then I will load the 6.1 version 64bits of pharo

**Comment by YvanGuifo** [comment]
After updating the operating system. I loaded the 64 bit version of Pharo 6.1; I was able to load kendrick and to check that everything works normally I try to execute a script already registered and when I do it there is a sudden interruption of Pharo which stops immediately then the following message 'Pharo has left of unforeseen way. I did this maneuver several times.
