### ISSUE TITLE
Visualization problem with Kendrick

### ISSUE THREAD

**Issue by YvanGuifo** [UMMISCO/kendrick#102]
Good afternoon, everyone,
Since yesterday I have a problem that is a little annoying.
Indeed, the models that worked as the first model no longer work. While I had made a local backup with Monticello Browser.
To find out a little more, I executed the block of code made up of the entities (KendrickModel, Composition, Scenario and Simulation) and there was no problem but when I include the Visualization entity it seems to have a problem. And I can't solve it.

It seems that the problem comes from the exportToPng element of the Visualisaion entity.
I use Pharo 6.1 64-bit version.

I attach two files highlighting the problem encountered.

Thank you.
<img width="1524" alt="Capture d’écran 2019-11-25 à 10 12 26" src="https://user-images.githubusercontent.com/56076081/69548706-1a5d7700-0f98-11ea-93a8-077fb9f9d0dc.png">
<img width="1524" alt="Capture d’écran 2019-11-25 à 10 16 36" src="https://user-images.githubusercontent.com/56076081/69548725-25b0a280-0f98-11ea-9d6b-6ec04e9fe496.png">

**Comment by SergeStinckwich** [comment]
Can you put the code of the model here ?

**Comment by YvanGuifo** [comment]
KendrickModel SIR
	attribute: #(status -> S I R);
	parameters: #(beta lambda gamma);
	transitions: #(
		S -- lambda --> I.
		I -- gamma --> R.
	);
	lambda: #(beta*I/N).
	
Composition Model1
	model: 'SIR'.
	
Scenario M1Parameters
	 on: 'Model1';
	 populationSize: 100;
    beta: 0.1; 
    gamma: 1/30; 
	 S: 90;
	 I: 10;
	 others: 0.
	
Simulation M1Sim gillespie
	scenarios: #(M1Parameters);
	from: 0.0; 
	to: 365; 
	step: 1.
	
Visualization M1DiagramViz diagram 
	for: 'M1Sim';
	xLabel: 'Time (Days)';
	exportToPng.

**Comment by SergeStinckwich** [comment]
Was not able to reproduce ... There is maybe a bug, but this is not clear why.
