### ISSUE TITLE
Visualization problem when the population size is large

### ISSUE THREAD

**Issue by YvanGuifo** [UMMISCO/kendrick#122]
The problem comes from the fact that in these cases there is no curve. I think that the size of the populations in the compartments and no scale plays a major role.

An example of code where we encounter this problem.
```Smalltalk
| model simulator dB |
	model := KEModel new.
	model addAttribute: #status value: #(#S #I #R).
	model atCompartment: {(#status -> #S)} put: 16106323 atOthersPut: 0.
	model atCompartment: {(#status -> #I)} put: 202.
	model
		addParameters:
			{
			 (#lambda -> -66.0177).
			 (#gamma -> 16.749)}.
	model
		addTransitionFrom: {(#status -> #S)}
		to: {(#status -> #I)}
		probability: [ :m | m atParameter: #lambda].
	model 
		addTransitionFrom: {(#status -> #I)} 
		to: {(#status -> #R)} 
		probability: [ :m | model atParameter: #gamma ].
	simulator := KESimulator
		new: #Gillespie
		from: 0.0
		to: 250
		step: 50.
	simulator executeOn: model.
	dB := KEDiagramBuilder new.
	dB addData: (simulator timeSeriesOutputsAt: {(#status -> #I)}).
	dB  xLabel: 'Time (days)'.
	dB  yLabel: '(New infections per day)'.
	dB legendTitle: 'Comportmental model with power law'.
	dB open

```

**Comment by SergeStinckwich** [comment]
Even there is no graphical result, did you try to plot the results with another tool?

**Comment by SergeStinckwich** [comment]
I try to run your code but it takes a lot of time apparently. It would be interesting to run it with a time profiler to know where all the time is spend in the code.

There should be a bug somewhere because we obtain a series with only one item for t=0 with #(R)= 16106323 and #(I)=202. You can inspect the simulator and check the timeSeriesOutputs

**Comment by SergeStinckwich** [comment]
You should try to step the simulation when simulator ``executeOn: model``, especially when new data are added in the series. From a 2min examination of the code, I can see that the execution never call ``saveCompartmentsValueAtTime:`` (or very occasionally) except for the initial values of the compartments. You should investigate why.

**Comment by SergeStinckwich** [comment]
This is not a visualisation problem but a problem linked to the way Gillespie simulation are done. Simulation API considerered that the step are regularly spaced and this is not the case in Gillespie where the step of simulation is computed by the simulation itself. This problem does not occur with Tau-Leap simulation and the simulation is also much faster. I open #125 to solve this issue.
