### ISSUE TITLE
SEIIRS model in Library/KendrickModel does not work

### ISSUE THREAD

**Issue by abous** [UMMISCO/kendrick#27]
When we test SEIIRS model in Library/KendrickModel under Ubuntu 17.04, we have the following problem: 
Author: aboubakar

KendrickModel class(KendrickInternalDSLEntities class)>>entityExistsIn:
[ inDisk := self entityFilesDir / self asString
	/ (anId asString , '.kendrick').	"library"
^ self entityExistsIn: inDisk ] in KendrickModel class(KendrickInternalDSLEntities class)>>pathLookUpFor:
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
NotFoundError(Exception)>>signal
NotFoundError(Exception)>>signal:
NotFoundError class(Exception class)>>signal:
KendrickModel class(KendrickInternalDSLEntities class)>>entityExistsIn:
[ ^ self entityExistsIn: inDisk ] in KendrickModel class(KendrickInternalDSLEntities class)>>pathLookUpFor:
BlockClosure>>on:do:
KendrickModel class(KendrickInternalDSLEntities class)>>pathLookUpFor:
KendrickModel class(KendrickInternalDSLEntities class)>>withId:
KendrickModel(KendrickInternalDSLEntities)>>extends:
KendrickModel>>extends:
UndefinedObject>>DoIt
OpalCompiler>>evaluate
RubSmalltalkEditor>>evaluate:andDo:
RubSmalltalkEditor>>highlightEvaluateAndDo:
[ textMorph textArea editor highlightEvaluateAndDo: ann action.
textMorph shoutStyler style: textMorph text ] in [ textMorph textArea
	handleEdit: [ textMorph textArea editor highlightEvaluateAndDo: ann action.
		textMorph shoutStyler style: textMorph text ] ] in GLMMorphicPharoScriptRenderer(GLMMorphicPharoCodeRenderer)>>actOnHighlightAndEvaluate:
RubEditingArea(RubAbstractTextArea)>>handleEdit:
[ textMorph textArea
	handleEdit: [ textMorph textArea editor highlightEvaluateAndDo: ann action.
		textMorph shoutStyler style: textMorph text ] ] in GLMMorphicPharoScriptRenderer(GLMMorphicPharoCodeRenderer)>>actOnHighlightAndEvaluate:
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess

**Comment by npapoylias** [comment]
Can you provide info on your installation method ? 

Did you use the installation script, or just load the Configuration ? 
(Normally both should work, but there are differences between the 
platforms).

I will check while going over our new documentation

**Comment by SergeStinckwich** [comment]
We install with the installation script. It was working on Mac OS X but not on Linux.


Envoyé de mon iPhone

**Comment by npapoylias** [comment]
Thanx ! good to know, I have an earlier version of ubuntu that I can check with.

**Comment by SergeStinckwich** [comment]
Apparently every time we build a model that is an extension (extends) of another one, there is a failure.

**Comment by npapoylias** [comment]
This was an issue only in ubuntu due to the zero-install folder layout
(checked all 3 platforms today).

This is now fixed when compiling 0.42 and/or using the pre-compiled version for Linux.

**Comment by SergeStinckwich** [comment]
ok thank you Nick. Next time, can you give the name of the commit ?

**Comment by SergeStinckwich** [comment]
Integrated in Kendrick-SergeStinckwich.626
