### ISSUE TITLE
Remove KEPRIMSGenerator and KEPRIMSVisitor

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#30]
Never implemented. I propose to remove them from the code.

**Comment by btmanh** [comment]
Done on Version 581

**Comment by SergeStinckwich** [comment]
Can you check your commit. Your fix remove a lot of classes like Composition, Scenario, etc ...
Not integrated at the moment.

**Comment by SergeStinckwich** [comment]
Done in Kendrick-SergeStinckwich.587
