### ISSUE TITLE
Splash Logo for KendrickUI (in dev and fullscreen modes)

### ISSUE THREAD

**Issue by npapoylias** [UMMISCO/kendrick#35]
Polishing for BMC, commited on Kendrick-NickPapoulias.591
and ConfigurationOfKendrick-NickPapoulias.97 (for 0.42)

**Comment by npapoylias** [comment]
refactored to a separated method and tested with 592 (and updated Configuration)

**Comment by SergeStinckwich** [comment]
merge with last version Kendrick-SergeStinckwich.593

**Comment by SergeStinckwich** [comment]
Thank you for having done a logo, but I want something a bit more stylish than the head on Mc Kendrick :-) We need some graphic designer !

**Comment by npapoylias** [comment]
Yes, this is a place holder, so that the software looks more polished.

**Comment by SergeStinckwich** [comment]
I made a list of possible icons here : #36
