### ISSUE TITLE
Troubles in KEIndexVariable and KESimulator's subclasses

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#41]
According to Mai Anh, we can't execute a Kendrick model like this:

```Smalltalk
    model := KEModel new population: (KEPopulation size: 27500).
    model attributes: {#status->#(#S #E #I #R)}.
    model atCompartment: {#status->#S} put: #(#(500 4990)#(500 5000)#(500 5000)#(500 5000)#(500 5000))
     atOthersPut: #(#(0 0)#(0 0)#(0 0)#(0 0)#(0 0)).
    model atCompartment: {#status->#S}
             put: #(#(0 10)#(0 0)#(0 0)#(0 0)#(0 0)).
    model atParameter: #N
     assignValue: #(#(500 5000)#(500 5000)#(500 5000)#(500 5000)#(500 5000)).
    model
         atParameter: #mu
         assignValue: #(
                #(0.000365 0.00137)
                #(0.000365 0.00137)
                #(0.000365 0.00137)
                #(0.000365 0.00137)
                #(0.000365 0.00137)).
    model
         atParameter: #sigma
         assignValue: #(#(0.5 0.67)#(0.5 0.67)#(0.5 0.67)#(0.5 0.67)#(0.5 0.67)).
    model
         atParameter: #gamma
         assignValue: #(#(0.25 0.233)#(0.25 0.233)#(0.25 0.233)#(0.25 0.233)#(0.25 0.233)).
    model
         atParameter: #nu assignValue: 0.00274.

    model
         atParameter: #rho
         assignValue: {0.03*#(#(0 1 0 0 0)#(0 0 1 0 0)#(0 0 0 1 0)#(0 0 0 0 1)#(1 0 0 0 0))
  . 0.1*#(#(0 1 0 0 0)#(0 0 1 0 0)#(0 0 0 1 0)#(0 0 0 0 1)#(1 0 0 0 0))}.
    model
         atParameter: #beta assignValue: #(#(0 0.21) #(0 0.42)).

    model
         atParameter: #p assignValue: (1 to: 5).

    model
        atParameter: #q assignValue: (1 to: 5).

    model
         atParameter: #s assignValue: (1 to: 2).

    model
         atParameter: #i assignValue: (1 to: 2).

    model addEquation:
('S[p][s]:t=mu[p][s]*N[p][s]-sum(i,beta[i][s]*I[p][i])/N[p][i]*S[p][s]-mu[p][s]*S[p][s]+sum(q,rho[s][p][q]*S[q][s])-sum(q,rho[s][q][p])*S[p][s]+nu*R[p][s]').

    model addEquation:
('E[p][s]:t=sum(i,beta[i][s]*I[p][i])/N[p][i]*S[p][s]-sigma[p][s]*E[p][s]-mu[p][s]*E[p][s]+sum(q,rho[s][p][q]*E[q][s])-sum(q,rho[s][q][p])*E[p][s]').

    model addEquation:
('I[p][s]:t=sigma[p][s]*E[p][s]-gamma[p][s]*I[p][s]-mu[p][s]*I[p][s]+sum(q,rho[s][p][q]*I[q][s])-sum(q,rho[s][q][p])*I[p][s]').

    model addEquation:
('R[p][s]:t=gamma[p][s]*I[p][s]-mu[p][s]*I[p][s]-nu*R[p][s]+sum(q,rho[s][p][q]*R[q][s])-sum(q,rho[s][q][p])*R[p][s]').
   
   simulator := KESimulator new: #RungeKutta from: 0 to: 500 step: 1.
   simulator executeOn: model.
   db := KEDiagramBuilder new.

   f := [:name| |d tmp|
        tmp := (simulator timeSeriesAt: name) collect: [ :e| e value ].
        d := OrderedCollection new.
        1 to: tmp first data size do: [ :k| d add: (tmp collect: [:e| e data at: k]) sum ].
        (KETimeSeries from: d withIndex: tmp first index) compartment: (STON fromString: name)
        ].
   db data: { 
        (f value: '{#status:#I, #species:#bird}'). 
        (f value: '{#status: #I, #species: #human}') }.
   db xLabel: 'Time (days)'.
   db legendTitle: 'Total of infectious'.
   db legends: { 'birds'. 'humans' }.

   db open.
```

We should modify methods named "executeWithModel" of ```KEIndexVariable``` and "executeOn" of ```KESimulator``` classes

**Comment by SergeStinckwich** [comment]
We can't ? we does it mean ? There is an error ? this is not correct from a conceptual point of view ?

**Comment by SergeStinckwich** [comment]
Is this issue still valid or I can close ?

**Comment by nguyentienthanh812** [comment]
Yes, it still is valid :(.

**Comment by nguyentienthanh812** [comment]
I have fixed this issue in case RungeKutta algorithm. Now I am working on Gillespie one,

**Comment by SergeStinckwich** [comment]
Please give the commit number and put a ready tag here if you want your code to be integrated in master.

**Comment by SergeStinckwich** [comment]
I had a look to your commit : Kendrick-nguyentienthanh.656

Several problems : 
- one test is red: ``KEIndexedVariableTest>>testIndexedExpression``.
- some methods are decompiled like : KEBinaryExpression>>calculateArraysBetween: arg1 with: arg2 All arguments names are lost.
- try to avoid methods with names like : calculate:with:at:andStoreIn:, calculateArraysBetween:with:, etc ... Their names are very vague (every method do a computation or a calculation) and this is very difficult to know what they are doing.
- some methods are too long. Have a look to the critics on the system browser below. The system tells you some advices on your code.

**Comment by nguyentienthanh812** [comment]
Thank you.
My bad :(. 
I have committed new code with:
+ green test in KEIndexedVariableTest >>testIndexedExpression
+ delete some vague methods.
+ modify some long methods
+ write some tests to explain how my new methods work
The new version is 657.

**Comment by SergeStinckwich** [comment]
When I see code like following, I'm a bit afraid : 

```Smalltalk
KESimulator>>sum: anArray
	"self new sum: #(#(1 1) #(2 2) #(3 3))"
	"self new sum: #(1 2 3)"
	|first api temp|
	first := anArray first .
	first isNumber ifTrue: [ ^(anArray sum). ].
	first isArray ifTrue: 
		[ 
			api := KEBinaryExpression new.
			api op: #+.
			temp := api convertToAnArray: 0 inFormat: first.
			anArray do: [ :each| temp := api calculateArraysBetween: each with: temp ].
			^temp.
		].
```

Why we need to introduce such method in a Simulator, why the argument is an Array ? an Array of what ? We need to understand what are arguments by reading the API and this is not the case. Sometimes this is a number, sometimes this an array number, sometimes something else ... This kind of code is bad ... We should not determine what to do according to the type.

```KESimulatorTest>>testAfterSimulationOfSIRModelThereAreThreeTimeSeries```is red.

You are not running all the tests before committing your code ?

**Comment by nguyentienthanh812** [comment]
Sorry.
The method sum of KESimulator, it implemented one of my approaches to solve this issue. But after several days, I detected this approach was wrong and no longer used it (and its methods like sum of KESimulator).
 
However, I forgot to remove it :(

About running all the test, I tried to run every tests but I selected every statements like "self new test...". Maybe in this way, I missed out on some test.

I have found a way to run all tests. 

![image](https://user-images.githubusercontent.com/30106741/29168691-31b0c664-7dfa-11e7-8e90-ba223d099338.png)


KESimulatorTest>>testAfterSimulationOfSIRModelThereAreThreeTimeSeriesis failed due to my bug, and I will fix it soon. :(

**Comment by SergeStinckwich** [comment]
Don't feel sorry, you are here to learn.

You can run tests individually by clicking on green/red dot close to the method, or all the tests of a class by clicking the dot close to the name of the class. You can run all the Kendrick tests, by using the Test Runner in the world menu.

Try to do small commits that fix a well defined problems/enhancements. Small fixes are easier for me to understand and check.

Every time you commit, check (with changes) what you commit. Do some cherry-picking with Kommitter if you want to select only a subset of your changes.

**Comment by nguyentienthanh812** [comment]
I dont know why but I could not use Kommitter in the past. Today, I re-install Moose and now I can pick a subset of my changes by using Kommitter.

I commit my new code and all tests are green as well.

**Comment by SergeStinckwich** [comment]
Kommitter is a little bit buggy ...

**Comment by SergeStinckwich** [comment]
Which version should I integrate ⁉️  Please help the work of the integrator (me).

**Comment by nguyentienthanh812** [comment]
It is nguyentienthanh.658 :). Tomorrow I will commit a new version which fixes issue in Gillespie case.

**Comment by SergeStinckwich** [comment]
Integrated in Kendrick-SergeStinckwich.668. I close this issue. Please introduce new issues for further enhancements.
