### ISSUE TITLE
Versionner does not work with Kendrick 

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#47]
There is a problem with DSL code apparently.

<img width="1146" alt="screen shot 2017-07-25 at 15 48 59" src="https://user-images.githubusercontent.com/327334/28578337-61149a8a-7151-11e7-9d81-87c15699300d.png">

**Comment by npapoylias** [comment]
This is probably related to the latest moose that we are using. Fixed today (again) the configuration to skip the moose baseline when loading.  I will have a closer look when I have time

**Comment by SergeStinckwich** [comment]
Thank you Nick ! These configuration problems are annoying ... We will take some time later, to have something working appropriately.

**Comment by SergeStinckwich** [comment]
Fixed in Kendrick-SergeStinckwich.683
