### ISSUE TITLE
KEIndexedVariableTest has no test at all

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#52]
There is no test in ```KEIndexedVariableTest``` class but code. A test class is only to tests features of the code.

**Comment by nguyentienthanh812** [comment]
Oops. I added two test cases in this class. The first one is "exampleCreateIndexedValue" and the last one is "exampleIndexedExpression". They are in revision 643. 

![image](https://user-images.githubusercontent.com/30106741/28755601-cf6c8e30-7588-11e7-9cde-8f26409e7f3d.png)
![image](https://user-images.githubusercontent.com/30106741/28755607-e1f288ac-7588-11e7-9cfb-91943b72abd4.png)

**Comment by SergeStinckwich** [comment]
These are not tests !

Tests just start with testXXXX or they are not tests and they don't appear in the test runner. Looks at other tests in the system.

**Comment by nguyentienthanh812** [comment]
Thank you. I change their names and commit my code as well. My revision is 646.

**Comment by SergeStinckwich** [comment]
ok integrated in last version
