### ISSUE TITLE
Is it a bug or does my MOOSE have trouble?

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#54]
I execute the exampleRK4SolverOnSIRMultiHostModel (in KEDeterministicExamples) and receive the Error like this.

![imageedit_1_2894712641](https://user-images.githubusercontent.com/30106741/28829401-ce55faf6-76fd-11e7-9e9c-b4d103a0011e.png)

Does anyone have the same trouble by chance?
Thank you

**Comment by SergeStinckwich** [comment]
There is no problem for me. This is an FFI problem apparently, nothing related to Kendrick I guess. Try to use the debugger to solve your problems before posting here.
