### ISSUE TITLE
CI does not work for Linux&Mac, only for windows

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#55]
Apparently this is link to this problem with MOOSE 6.1:
```
MetacelloConflictingProjectError: Load Conflict between existing BaselineOfStateSpecs [baseline] from github://dionisiydk/StateSpecs:v2.4.x and ConfigurationOfStateSpecs stable from http://www.smalltalkhub.com/mc/dionisiy/StateSpecs/main
```

**Comment by npapoylias** [comment]
This is fixed for zero-install (rechecked this morning). So this is smth in the CI-git configuration. In general these can be treated by reproducing locally (https://github.com/hpi-swa/smalltalkCI#how-to-local), I 'll have a look

**Comment by npapoylias** [comment]
Fixed baseline on dev configuraiton version, local CI passes. 
Travis CI has issues with  downloading moose from inria.

Name: ConfigurationOfKendrick-NickPapoulias.101
Author: NickPapoulias
Time: 2 August 2017, 7:49:44.686018 pm
UUID: 9fd44ea0-2a12-0d00-a5d8-4d800988c327
Ancestors: ConfigurationOfKendrick-NickPapoulias.100

++ CI is loading the development: (version and corresponding selector) -- moving to 0.11 baseline to avoid moose loading errors

**Comment by npapoylias** [comment]
Linux, Mac are now green but windows went red on us.. There is an instability with moose
downloads on the CI servers (from appveyor):

Downloading Moose-6.0 image...
curl **failed to download** https://ci.inria.fr/moose/job/moose-6.0/lastSuccessfulBuild/artifact/moose-6.0.zip to '/cygdrive/c/smalltalkCI-master/_cache/Moose-6.0.zip'.

**Comment by npapoylias** [comment]
All green ;) Closing.

**Comment by SergeStinckwich** [comment]
Great ! Thank you Nick !
