### ISSUE TITLE
Support of indexed equations with Gillespie Simulator

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#60]
I'm very glad to announce that revision NguyenTienThanh.669 has been committed.

Now KEGillespieSimulator can handle a model with indexed equations like this

	model := KEModel new.
	model population: (KEPopulation size: 13000).
	model addAttribute: #status value: #(#S #I #R).
	model addAttribute: #species value: #(#mosquito #reservoir1 #reservoir2).
	model atParameter: #mu assignValue: {12.17 . 0.05 . 0.05}.
	model atParameter: #N assignValue: #(10000 1000 2000).
	model atParameter: #gamma assignValue: 52.
	model atParameter: #beta assignValue: #(#(0 0.02 0.02) #(0.02 0 0) #(0.02 0 0)).
	model atParameter: #i assignValue: (1 to: 3).
	model atParameter: #j assignValue: (1 to: 3).
	
	model addEquation: 'S[i]:t=mu[i]*N[i]-sum(j, beta[i][j]*I[j])*S[i]-mu[i]*S[i]'.
	model addEquation: 'I[i]:t=sum(j, beta[i][j]*I[j])*S[i]-(mu[i]+gamma)*I[i]'.
	model addEquation: 'R[i]:t=gamma*I[i] - mu[i]*R[i]'.

	model atCompartment:  {(#status -> #S). (#species -> #mosquito)} 	put: 9999.
	model atCompartment:  {(#status -> #I). (#species -> #mosquito)} 	put: 1.
	model atCompartment:  {(#status -> #R). (#species -> #mosquito)}  put: 0.
	model atCompartment:  {(#status -> #S). 	(#species -> #reservoir1)} put: 1000.
	model atCompartment:  {(#status -> #I). (#species -> #reservoir1)} put: 0.
	model atCompartment:  {(#status -> #R). 	(#species -> #reservoir1)} put: 0.
	model atCompartment: {(#status -> #S).  (#species -> #reservoir2)} put: 2000.
	model atCompartment:  {(#status -> #I).  (#species -> #reservoir2)} 	put: 0.
	model atCompartment:  {(#status -> #R). 	(#species -> #reservoir2)} put: 0.

        simulator := KESimulator new: #Gillespie  from: 0.0 to: 0.5 by: 0.0027.
	simulator executeOn: model.
	db := KEDiagramBuilder new data: (simulator allTimesSeriesContaining: '{#status: #I}') sqrt.
	db open

My result:
![pic](https://user-images.githubusercontent.com/30106741/29237085-ece075d2-7f40-11e7-8307-bcfc10391497.jpg)

The result is a bit like graph of Example 2 [here](https://github.com/UMMISCO/kendrick/wiki/Example-2:-Multi-species-model)

Example 2:
![example2](https://user-images.githubusercontent.com/30106741/29237098-3b5f3748-7f41-11e7-93b3-d824efaff65e.png)

**Comment by btmanh** [comment]
what is the parameter c?

--------------------
Bui Thi Mai Anh
Lecturer at Software Engineering Department
School of Information and Communication Technology
Hanoi University of Technology,
1 Dai Co Viet Street, Hai Ba Trung District, Hanoi, Vietnam

**Comment by nguyentienthanh812** [comment]
Oops. It is just a variable to run this test:
        tmp := KEIndexedVariable new.
	tmp symbol: #beta.
	tmp addIndex: (KEVariable new symbol: #i).
	tmp addIndex: (KEVariable new symbol: #c).	"c = 1"

	"beta[i][1]"
	self assert: (tmp evaluateWithModel: model) equals: #(0 0.02 0.02)
-------------------
I have removed it

**Comment by SergeStinckwich** [comment]
Integrated in Kendrick-SergeStinckwich.671
