### ISSUE TITLE
Support of indexed equations with IBM

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#61]
I'm working on "Indexed Equations with IBM algorithm". But when I run a model in exampleIBMSimulatorOnSIRMultiHostModel of class named KEIndividualBasedExample, I notice it generates a graph like this:
![pic](https://user-images.githubusercontent.com/30106741/29246457-8bf2f788-8024-11e7-8588-d4a8a87d55f3.jpg)

It is not a smooth one like RungeKutta algorithm or even Gillespie. Is it correct?
Does anyone have the same graph by chance?

**Comment by nguyentienthanh812** [comment]
My revision nguyentienthanh.671 makes KEIndividualBasedSimulator support indexed equations.

To integrate my code with the main branch, please use my revision nguyentienthanh.673 (because I merge it with sergestinckwich.671)

PS: I upload the graph of Indexed Equations model in case IBM algorithm.
![untitle111d](https://user-images.githubusercontent.com/30106741/29412283-4497c36c-8382-11e7-8d56-affe64d6c2f7.png)

**Comment by SergeStinckwich** [comment]
Thank you Tien. I had a look to your code. I'm not really satisfied because you add methods like ```createMoreAssociations: as``` and I dunno exactly what they are doing ...

I try to simplify code in ```KEIndividualBasedSimulator```but you add more layers of complexity. You increase all methods size 👎  ... For example in ```buildAgentsFromBirthTransitions```, why we have to check the type r (sometimes a number, sometimes an Array, ...). Why do we have to add an additional temporary variable like : ```additionalAssoc``` and the name of the variable give to information why we need it.

I don't know how you implement ```KEIndexedVariable```but I don't understand why we have to modify each simulation engines. Indexed variables should be considered as a set of variables and nothing should be changed in simulation engines.

**Comment by nguyentienthanh812** [comment]
When I fix the issue in IBM, I choose two models which are equivalent to each other. They are "`modelSIRKEModelPart`" and "`modelSIRMultiHost`" in class "`KEIndexedVariableTest`".

Both of them have SIR status and three species. The "`modelSIRKEModelPart`" uses `KEModelPart `and has no equation (I name it model A). In contrast, "`modelSIRMultiHost`" doesn't use `KEModelPart `and has three indexed equations (I name it model B)

I run IBM algorithm in two models A and B; then, I notice differences between number of loops and values of every variables in two cases.

![image](https://user-images.githubusercontent.com/30106741/29444488-1eb1f4d2-840a-11e7-936e-16a05fd6f657.png)
                  Figure 1. Method `buildAgentsFromBirthTransitions `of `KEIndividualBasedSimulator`

In case model A, `birthTransitions `has three elements. In case model B, it has only one. 
![image](https://user-images.githubusercontent.com/30106741/29444758-5ae2c830-840c-11e7-8841-726fb03fb4c2.png)
Figure 2. Values of `birthTransitions `when I run IBM with two model A and B.

**Comment by nguyentienthanh812** [comment]
Now `buildAgentsFromBirthTransitions `has 3 loops in both model A and B. 
Next, the values of variables `r` and `p` in each loop.

![image](https://user-images.githubusercontent.com/30106741/29445420-e1aa8f84-8410-11e7-90e5-6deaf475fa8c.png)
Figure 3. The original code of `do` block in `buildAgentsFromBirthTransitions `

When execute the statement: `r := (t key probability value: model) abs`. (`t` is an association from `{#status->empty, #species->mosquito}` to `{#status->S, #species->mosquito}`), I notice:
 In case model A, `r` is a number 12.17. 
But in case model B, `r` is an array #(12.17 0.05 0.05). So I should write some statements to pick up 12.17 from the array.
![image](https://user-images.githubusercontent.com/30106741/29445940-a94fe8d4-8413-11e7-80e0-a615323da2bf.png)
Figure 4: Some statements to pick up right values from arrays.

Now, when execute `p := (PoissonGenerator lambda: rate * step)` next, we have same input "`rate*step`" in both case model A and B.

**Comment by nguyentienthanh812** [comment]
Of course, my modification makes some methods become long. I will try to reduce their sizes. :(

**Comment by nguyentienthanh812** [comment]
In conclusion, I think there are two issues:
1. "`transitions`" of `KEModel ` is wrong in case indexed equations. Model B, has three status and three species, but `KEModel `generates just six transitions (not enough). If `KEModel `can generate enough 18 transitions (like model A), I will remove "`additionalTrans`" and "`additionalAssoc`" in my code.

2. When evaluate the probability of transition `r := (t key probability value: model) abs`, in case indexed equations (model B), we receive an indexed values (an array) instead of a number. So we should write just one statement to pick up right value in this set.  For example: `rate := self project: r into: from.`

Note:
* model A is a model which uses KEModelPart, we can see its details in "modelSIRKEModelPart" of class "KEIndexedVariableTest".
* model B is a model which uses indexed equations, we can see its details in "modelSIRMultiHost" of class "KEIndexedVariableTest".

**Comment by nguyentienthanh812** [comment]
Well, let me see... Maybe I dont need to add more methods like this. There are still something wrong with my KEIndexedVariable

**Comment by nguyentienthanh812** [comment]
I commit my new code. In my revision, the simulator engines have no change and now they handle indexed equations.

Users can execute "`exampleRK4SolverSIRMultiHost`", "`exampleGillespieSolverSIRMultiHost`" and "`exampleIBMSolverSIRMultiHost`". All of them are models contains indexed equations.

I add new class named `KETransitionGenerator`. It will generate transitions from indexed equations of a model.

In case model has only transitions, `KETransitionGenerator `will automatically use all of them as "model transitions"

The old code has `KEEventGenerator`. In my new code, `KETransitionGenerator `will call method of `KEEventGenerator`. So then in `equationsToTransitions `of `KEComponent`, I write "`transitions := KETransitionGenerator from: self.`" instead of "`events := KEEventGenerator from: self.`"

To integrate, we can merge with `Kendrick-nguyentienthanh.697`

**Comment by SergeStinckwich** [comment]
Integrated in Kendrick-SergeStinckwich.698
