### ISSUE TITLE
Clean-up of test-inspectors, changing population size on intensive tests

### ISSUE THREAD

**Issue by npapoylias** [UMMISCO/kendrick#65]
Name: Kendrick-NickPapoulias.701
Author: NickPapoulias
Time: 20 September 2017, 4:16:13.566022 pm
UUID: d806ee5a-0116-0d00-a78a-03450988c327
Ancestors: Kendrick-NickPapoulias.700

removing test inspectors and changing population
size in time consuming mosquito scripts

**Comment by SergeStinckwich** [comment]
Integrated in Kendrick-SergeStinckwich.702
