### ISSUE TITLE
Can not commit my code to Kendrick github

### ISSUE THREAD

**Issue by nguyentienthanh812** [UMMISCO/kendrick#72]
My computer is Windows 10, 64 bit, and my Pharo is downloaded from [Kendrick-0.42-Windows](https://gitlab.com/ird-ummisco-npapoylias/kendrick-extentions/raw/master/Kendrick-0.42-Windows.zip).
.
I attempted to commit my code several times. Every time, I tried to follow the guide of [CONTRIBUTING.md](https://github.com/UMMISCO/kendrick/blob/master/CONTRIBUTING.md).

At the first step, I completely update Iceberg. 

![image](https://user-images.githubusercontent.com/30106741/43652717-31bb4f7c-9770-11e8-8cb6-404960435146.png)
                                                 

I got that, I guess it mean succeed.

![image](https://user-images.githubusercontent.com/30106741/43652879-a8dca48e-9770-11e8-905b-536f3b4bca4e.png)

As "setup Iceberg", I simply checked the box:

![image](https://user-images.githubusercontent.com/30106741/43652819-7ffa5a84-9770-11e8-9961-4aff05dc91fa.png)

As "Fork the Kendrick repository", I clicked the "Fork" button and saw:

![image](https://user-images.githubusercontent.com/30106741/43653219-a373f9c4-9771-11e8-9180-635b69df754a.png)
.

At "Load your fork version of Kendrick in your image", I used this text:

![image](https://user-images.githubusercontent.com/30106741/43653308-dec50ed2-9771-11e8-8607-d6c215fd37d0.png)

The first problem is here, it always shows an error:

![image](https://user-images.githubusercontent.com/30106741/43653445-47e42808-9772-11e8-8123-a1440ae4e093.png)
 

If I put this step away, I go to "Send the PR to the original Kendrick repo". And I don't know how to "send" Pull Request.

If I ignor the step "Send the PR to the original Kendrick repo", I use Iceberg to commit. I carefully check new methods of classes, and then press "Commit" button of Iceberg. And then I receive this error:
 
![image](https://user-images.githubusercontent.com/30106741/43654177-9b082712-9774-11e8-99bd-9ce341bc88ee.png)

I already implemented Bansal's idea for regular random network, and - my code - it works but I can't commit my code to Kendrick repo. 
Here, I show you two results, the left one is my implementation of Bansal idea; the right one is original result of compartmental contact network (you can obtain as you run "self new exampleIBMSimulatorOnSIRModelWithContactNetworkAmongIndividuals")
Two results are similar, it means I can take advantage of my code for other networks

![image](https://user-images.githubusercontent.com/30106741/43654348-242271d8-9775-11e8-95af-d752a1eba020.png)

**Comment by nguyentienthanh812** [comment]
Today, as I attempted to "Load last dev version of Kendrick", I received it

![image](https://user-images.githubusercontent.com/30106741/43672632-69764658-97dc-11e8-8198-766a6575dd30.png)

**Comment by SergeStinckwich** [comment]
Don't use Kendrick-0.42, because it already contain an old version of Kendrick. Use the github version instead. Details to install are here: https://github.com/UMMISCO/kendrick/blob/master/CONTRIBUTING.md
