### ISSUE TITLE
KEPopulation created with a size has no size

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#73]
```KEPopulation``` initialize with a size has no size. This is a bit strange ...

```(KEPopulation size: 100) size``` => returns an error.

**Comment by SergeStinckwich** [comment]
I think the user should not be allowed to initialize a population with an initial size. The size of a population should be computed from the compartements that split the population.

This will simplify a lot the code because at the moment, we have to test everytime we add a compartment, we have to test the initial size ... This is non-sense.

**Comment by SergeStinckwich** [comment]
Solution:
- Remove ```KEPopulation>>size:```
- Remove ```KEPopulation>>initialSize:``` and ```KEPopulation>>initialSize```
- Add an initialize method on KEPopulation that will initialize compartments as an empty collection
- remove tests of size of population in ```KEModel>>atStatus:put:``` and ```KEModel>>atCompartment:put:```
- Remove all users of these methods

**Comment by btmanh** [comment]
I think a population should have an initial size. When you add a concern to a model, the population then is split into compartments and the total size of all compartments should be equal to the initial size of the population. This is a constraint, so that users cannot assign any value to a compartment.

**Comment by SergeStinckwich** [comment]
The constrain is not very well tested only when you add a new compartment ...
When you add a concern, you know the size of the population, you just have to add the compartment sizes.

Can you give an example of where you need to fix the population number at the beginning ?

**Comment by btmanh** [comment]
This constraint is tested when we initalize the size of compartments. We donot add a new compartment, compartments are automatically obtained as result of combining concerns.
I think whenever we assign an initial size to a compartment, the total size of population should be verified. I really think it is necessary.

**Comment by SergeStinckwich** [comment]
Apply DRY principle: https://en.wikipedia.org/wiki/Don't_repeat_yourself

**Comment by SergeStinckwich** [comment]
Everything was remove to fix this issue except KEPopulation>>size: because used in the DSL.
A new issue will be open for that problem.
