### ISSUE TITLE
Having one syntax for compartments, not two

### ISSUE THREAD

**Issue by SergeStinckwich** [UMMISCO/kendrick#90]
Can we simplify the syntax to represent a compartment ? At the moment, we have two syntax : 
- ``'{#status:#I}'``
- ``{#status -> #I}``

Can we use only second syntax ?

Having multiple syntaxes introduce a lot of complexity.

**Comment by btmanh** [comment]
Yes, Serge. I intend to do this too. Keep the second i think and remove the first.

**Comment by SergeStinckwich** [comment]
Ok I will do it.
