### ISSUE TITLE
The bugs with Kendrick on Pharo 7

### ISSUE THREAD

**Issue by YvanGuifo** [UMMISCO/kendrick#98]
Whenever I run a model with Kendrick on Pharo 7 I have bugs or errors. Even when I make a simple copy of the models of the kendrick benchmark. The execution of the model does not succeed.

**Comment by SergeStinckwich** [comment]
Yvan, you have to learn how to do bugs report ! You need to be much more informative if you want to someone reply to you. Which version of Pharo, which OS, wich version of Kendrick you use ? What model breaks ? What are exact message error ? etc ...

**Comment by SergeStinckwich** [comment]
I fix the execution errors in last commits.
